apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradepulse-api
spec:
  replicas: 5
  template:
    metadata:
      annotations:
        security.tradepulse.dev/log-level: "warn"
        security.tradepulse.dev/mtls-required: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
      labels:
        environment: production
    spec:
      priorityClassName: tradepulse-critical
      nodeSelector:
        environment: production
      tolerations:
        - key: environment
          operator: Equal
          value: production
          effect: NoSchedule
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
      containers:
        - name: tradepulse-api
          resources:
            requests:
              cpu: "750m"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
          env:
            - name: TRADEPULSE_ENVIRONMENT
              value: production
            - name: TRADEPULSE_RATE_LIMIT_TPS
              value: "1200"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: tradepulse-kafka-client
                  key: bootstrap.servers
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: tradepulse-kafka-client
                  key: security.protocol
            - name: KAFKA_SSL_CAFILE
              value: /etc/tradepulse/kafka/ca.crt
            - name: KAFKA_SSL_CERTFILE
              value: /etc/tradepulse/kafka/client.crt
            - name: KAFKA_SSL_KEYFILE
              value: /etc/tradepulse/kafka/client.key
            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                secretKeyRef:
                  name: tradepulse-kafka-client
                  key: sasl.mechanism
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tradepulse-kafka-client
                  key: sasl.username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tradepulse-kafka-client
                  key: sasl.password
          volumeMounts:
            - name: kafka-client-tls
              mountPath: /etc/tradepulse/kafka
              readOnly: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: tradepulse-api
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - tradepulse-api
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: kafka-client-tls
          secret:
            secretName: tradepulse-kafka-client
