################################################################################
# Dependabot Configuration for TradePulse
#
# Automatically checks for dependency updates and creates pull requests.
# Configured to run weekly checks for Python pip packages.
#
# Purpose:
# - Keep dependencies up-to-date with latest security patches
# - Reduce manual effort in dependency maintenance
# - Ensure timely application of security fixes
#
# Learn more: https://docs.github.com/en/code-security/dependabot
################################################################################

version: 2

updates:
  # Python dependencies (pip)
  # Scans requirements.txt, requirements-dev.txt, and other pip files
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates every Monday at 9:00 AM UTC
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    
    # Automatically open pull requests for security updates
    open-pull-requests-limit: 10
    
    # Rebase strategy for PR updates
    rebase-strategy: "auto"
    
    # Add reviewers and assignees to PRs
    reviewers:
      - "neuron7x"
    
    # Labels for categorization
    labels:
      - "dependencies"
      - "security"
      - "automated"
    
    # Commit message prefix
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
    # Group minor and patch updates together to reduce PR noise
    groups:
      production-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
