name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Fixes'
    labels:
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## 🚀 Highlights

  $CHANGES

  ## 🙌 Contributors

  $CONTRIBUTORS
no-changes-template: 'No changes in this release.'
version-resolver:
  major:
    labels:
      - 'semver:major'
  minor:
    labels:
      - 'semver:minor'
  patch:
    labels:
      - 'semver:patch'
  default: patch
