# SPDX-License-Identifier: MIT
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
  - repo: local
    hooks:
      - id: slotscheck
        name: slotscheck (core packages)
        entry: python -m slotscheck --module core --module backtest --module execution
        language: python
        additional_dependencies:
          - slotscheck==0.19.1
        pass_filenames: false
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
