codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project:
      default:
        target: auto          # бере за ціль coverage базової гілки
        threshold: 0%         # будь-яке зниження = fail
        informational: false
    patch:
      default:
        target: 100%          # весь новий/змінений код повинен бути покритий
        threshold: 0%
        informational: false

comment:
  layout: "reach, diff, flags, files"
  require_changes: false
  behavior: default
