apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tradepulse-api
  labels:
    app.kubernetes.io/name: tradepulse-api
    app.kubernetes.io/part-of: tradepulse
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tradepulse-api
  minReplicas: 3
  maxReplicas: 12
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 4
          periodSeconds: 60
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
        - type: Pods
          value: 2
          periodSeconds: 300
        - type: Percent
          value: 30
          periodSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Pods
      pods:
        metric:
          name: tradepulse_signal_to_fill_latency_quantiles_seconds
          selector:
            matchLabels:
              quantile: "0.95"
        target:
          type: AverageValue
          averageValue: 400m
    - type: External
      external:
        metric:
          name: tradepulse_orders_queue_depth
        target:
          type: AverageValue
          averageValue: "80"
