apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tradepulse-api
  labels:
    app.kubernetes.io/name: tradepulse-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: tradepulse-api
