apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tradepulse-api
spec:
  minReplicas: 2
  maxReplicas: 6
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 45
    scaleDown:
      stabilizationWindowSeconds: 180
