filebeat.autodiscover:
  providers:
    - type: docker
      cleanup_removed: true
      templates:
        - condition:
            equals:
              docker.container.labels.co.elastic.logs/enabled: "true"
          config:
            - type: filestream
              id: tradepulse-container-logs
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              parsers:
                - ndjson:
                    overwrite_keys: true
                    add_error_key: true
              fields:
                service.name: ${data.docker.container.labels.co.elastic.logs/module:tradepulse}
                environment: local
              fields_under_root: true
              ignore_older: 72h

processors:
  - add_host_metadata: ~
  - add_process_metadata: ~
  - drop_fields:
      fields: ["input", "agent"]

output.logstash:
  hosts: ["logstash:5044"]
