# SPDX-License-Identifier: MIT
global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: default
  routes:
    - matchers:
        - severity = "critical"
      receiver: paging
      continue: true
    - matchers:
        - severity = "warning"
      receiver: slack
      continue: true

receivers:
  - name: default
    email_configs:
      - to: alerts@tradepulse.local
        send_resolved: true
  - name: slack
    slack_configs:
      - api_url: ${SLACK_WEBHOOK_URL}
        channel: tradepulse-alerts
        title: "{{ template \"slack.title\" . }}"
        text: "{{ template \"slack.message\" . }}"
        send_resolved: true
  - name: paging
    pagerduty_configs:
      - routing_key: ${PAGERDUTY_ROUTING_KEY}
        severity: critical
        send_resolved: true

