apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kafka
    releaseName: tradepulse-kafka
    version: 27.0.0
    repo: https://charts.bitnami.com/bitnami
    includeCRDs: false
    valuesInline:
      fullnameOverride: tradepulse-kafka
      kraft:
        enabled: true
        clusterId: TrdPlsClusterK8s0001
      controller:
        replicaCount: 3
      listeners:
        client:
          protocol: SASL_SSL
          containerPort: 9093
        controller:
          protocol: PLAINTEXT
      externalAccess:
        enabled: true
        controller:
          service:
            type: LoadBalancer
        broker:
          service:
            type: LoadBalancer
            ports:
              - name: sasl
                port: 9094
                protocol: TCP
                targetPort: 9094
          autoDiscovery:
            enabled: false
      podSecurityContext:
        enabled: true
        fsGroup: 1001
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
      auth:
        interBrokerProtocol: SASL_SSL
        clientProtocol: SASL_SSL
        sasl:
          interBrokerMechanism: plain
          mechanisms:
            - plain
          interbroker:
            user: tradepulse-broker
          controller:
            user: tradepulse-controller
          client:
            users:
              - tradepulse
          jaas:
            clientUsers:
              - tradepulse
        existingSecret: tradepulse-kafka-sasl
      tls:
        type: PEM
        existingSecret: tradepulse-kafka-broker-tls
        autoGenerated: false
      metrics:
        jmx:
          enabled: true
        kafka:
          enabled: true
