name: Release Drafter with retries
inputs:
  github-token:
    description: GitHub token used to authenticate release-drafter requests.
    required: true
  config-name:
    description: Name of the release drafter configuration file.
    required: false
    default: release-drafter.yml
  retry-delay-seconds:
    description: Seconds to wait between retries.
    required: false
    default: '10'
runs:
  using: composite
  steps:
    - id: attempt1
      name: Release Drafter (attempt 1)
      continue-on-error: true
      uses: release-drafter/release-drafter@v6
      with:
        config-name: ${{ inputs.config-name }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Wait before retry #1
      if: steps.attempt1.outcome == 'failure'
      shell: bash
      run: sleep ${{ inputs.retry-delay-seconds }}
    - id: attempt2
      name: Release Drafter (attempt 2)
      if: steps.attempt1.outcome == 'failure'
      continue-on-error: true
      uses: release-drafter/release-drafter@v6
      with:
        config-name: ${{ inputs.config-name }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Wait before retry #2
      if: steps.attempt2.outcome == 'failure'
      shell: bash
      run: sleep ${{ inputs.retry-delay-seconds }}
    - id: attempt3
      name: Release Drafter (attempt 3)
      if: steps.attempt2.outcome == 'failure'
      uses: release-drafter/release-drafter@v6
      with:
        config-name: ${{ inputs.config-name }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Fail after retries
      if: steps.attempt3.outcome == 'failure'
      shell: bash
      run: |
        echo "Release Drafter failed after 3 attempts." >&2
        exit 1
