apiVersion: v1
kind: Secret
metadata:
  name: tradepulse-kafka-sasl
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: tradepulse
    app.kubernetes.io/managed-by: kustomize
stringData:
  client-passwords: REPLACE_ME_CLIENT_PASSWORD
  inter-broker-password: REPLACE_ME_INTER_BROKER_PASSWORD
  controller-password: REPLACE_ME_CONTROLLER_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: tradepulse-kafka-broker-tls
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: tradepulse
    app.kubernetes.io/managed-by: kustomize
stringData:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    REPLACE_ME_BROKER_CA
    -----END CERTIFICATE-----
  tls.crt: |-
    -----BEGIN CERTIFICATE-----
    REPLACE_ME_BROKER_CERT
    -----END CERTIFICATE-----
  tls.key: |-
    -----BEGIN PRIVATE KEY-----
    REPLACE_ME_BROKER_KEY
    -----END PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: tradepulse-kafka-client
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: tradepulse
    app.kubernetes.io/managed-by: kustomize
stringData:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    REPLACE_ME_CLIENT_CA
    -----END CERTIFICATE-----
  client.crt: |-
    -----BEGIN CERTIFICATE-----
    REPLACE_ME_CLIENT_CERT
    -----END CERTIFICATE-----
  client.key: |-
    -----BEGIN PRIVATE KEY-----
    REPLACE_ME_CLIENT_KEY
    -----END PRIVATE KEY-----
  security.protocol: SASL_SSL
  sasl.mechanism: PLAIN
  bootstrap.servers: REPLACE_ME_BOOTSTRAP_SERVERS
  sasl.username: tradepulse
  sasl.password: REPLACE_ME_CLIENT_PASSWORD
