apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradepulse-production

resources:
  - ../../namespaces/production
  - priorityclass.yaml
  - ../../base
  - ../../grafana

images:
  - name: ghcr.io/neuron7x/tradepulse
    newTag: stable

patches:
  - path: patches/deployment-high-availability.yaml

secretGenerator:
  - name: grafana-admin-credentials
    behavior: replace
    envs:
      - secrets/grafana-admin.env

generatorOptions:
  disableNameSuffixHash: true
