apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradepulse-production

resources:
  - ../../namespaces/production.yaml
  - priorityclass.yaml
  - ../../base

images:
  - name: ghcr.io/neuron7x/tradepulse
    newTag: stable

patches:
  - path: patches/deployment-high-availability.yaml
