ema_span: 32
vol_lambda: 0.94
alpha: 1.2
beta: 0.6
lambda_sync: 0.7
eta_ricci: 0.5
k_gain0: 2.0
theta0: 0.0
rho: 0.04
lam_S: 0.92
eta_k: 0.01
eta_theta: 0.001
pi_min: 0.01
pi_max: 1000.0
eps: 1.0e-08
ent_bins: 32
ent_xmin: -0.05
ent_xmax: 0.05
ent_decay: 0.975
