kuramoto:
  timeframes:
    - 60
    - 300
    - 900
    - 3600
  adaptive_window:
    enabled: true
    min_window: 50
    max_window: 500
    base_window: 200
  consensus_weights:
    M1: 0.1
    M5: 0.2
    M15: 0.3
    H1: 0.4
  hilbert:
    detrend: true
    method: "linear"

ricci:
  graph:
    n_levels: 20
    connection_threshold: 0.1
  temporal:
    window_size: 100
    n_snapshots: 10
    snapshot_interval: null
  ollivier:
    alpha: 0.5
    timeout: 1
  transition:
    derivative_window: 2
    jump_threshold: 0.3
    sigmoid_steepness: 10

composite:
  thresholds:
    R_strong_emergent: 0.80
    R_proto_emergent: 0.40
    coherence_min: 0.60
    ricci_negative: -0.30
    temporal_ricci: -0.20
    topological_transition: 0.70
  signals:
    min_confidence: 0.50
    confidence_boost:
      strong_emergent: 1.5
      chaotic: 0.5
    risk_multipliers:
      strong_emergent:
        base: 1.0
        confidence_scale: 0.5
      proto_emergent:
        base: 0.7
        confidence_scale: 0.3
      transition: 0.3
      chaotic: 0.3
      post_emergent: 0.2
      min: 0.1
      max: 2.0
  phases:
    strong_emergent:
      entry_direction: "temporal_ricci"
      exit_urgency: 0.1
    proto_emergent:
      entry_scale: 0.5
      exit_urgency: 0.3
    post_emergent:
      entry_signal: -0.3
      exit_urgency: 0.7
    transition:
      entry_signal: 0.0
      exit_urgency: "transition_score"
    chaotic:
      entry_signal: 0.0
      exit_urgency: 0.5

integration:
  data:
    min_history: 1000
    required_columns:
      - close
      - volume
    datetime_index: true
  performance:
    parallel_timeframes: true
    cache_graphs: true
    max_cache_size: 100
  logging:
    level: "INFO"
    log_signals: true
    log_metrics: true
    save_history: true
    history_path: "outputs/signal_history.csv"

backtest:
  trade_execution:
    entry_signal_threshold: 0.3
    exit_signal_threshold: 0.6
  position_sizing:
    base_size: 1.0
    use_risk_multiplier: true
    max_position: 2.0
  risk:
    use_confidence_filter: true
    min_confidence: 0.5
    stop_loss_multiplier: 1.5
    take_profit_multiplier: 2.0

monitoring:
  alerts:
    phase_change:
      enabled: true
      notify_on:
        - STRONG_EMERGENT
        - TRANSITION
    metric_thresholds:
      high_transition:
        metric: "topological_transition_score"
        threshold: 0.8
        action: "log"
      low_coherence:
        metric: "cross_scale_coherence"
        threshold: 0.3
        action: "log"
      extreme_risk:
        metric: "risk_multiplier"
        min: 0.1
        max: 1.8
        action: "alert"
  dashboard:
    update_interval: 60
    metrics_to_display:
      - kuramoto_R
      - consensus_R
      - temporal_ricci
      - topological_transition
      - phase
      - confidence
      - entry_signal
      - exit_signal

features:
  engineering:
    kuramoto_features:
      - consensus_R
      - cross_scale_coherence
      - dominant_timeframe_R
    ricci_features:
      - static_ricci
      - temporal_ricci
      - topological_transition_score
      - structural_stability
      - edge_persistence
    composite_features:
      - phase_encoded
      - confidence
      - entry_signal
      - exit_signal
      - risk_multiplier
  normalization:
    method: "robust"
    rolling_window: 500

experimental:
  kuramoto_extensions:
    higher_order_coupling: false
    adaptive_coupling_strength: false
  ricci_extensions:
    persistent_homology: false
    ricci_flow: false
  meta_learning:
    enabled: false
    update_thresholds: false
    strategy_evolution: false

metadata:
  version: "1.0.0"
  author: "TradePulse Development"
  description: "Kuramoto-Ricci Composite Indicator Configuration"
  created: "2024-10-06"
  last_modified: "2024-10-06"
