
kuramoto:
  timeframes: [60, 300, 900, 3600]
  adaptive_window:
    enabled: true
    base_window: 200

ricci:
  temporal:
    window_size: 100
    n_snapshots: 8
  graph:
    n_levels: 20
    connection_threshold: 0.1

composite:
  thresholds:
    R_strong_emergent: 0.80
    R_proto_emergent: 0.40
    coherence_min: 0.60
    ricci_negative: -0.30
    temporal_ricci: -0.20
    topological_transition: 0.70
  signals:
    min_confidence: 0.50
