# Default market-specific transaction cost configuration.
BTC-USD:
  commission_bps: 0.02
  spread_bps: 5.0
  slippage_model: square_root
  slippage_params:
    a: 0.0001
    b: 0.002
ES-mini:
  commission_per_contract: 1.25
  spread: 0.5
  slippage_model: fixed
  slippage_params:
    value: 0.25
CL-front:
  commission_model: percent
  commission_params:
    percent: 0.015
  spread_model: bps
  spread_params:
    bps: 12.5
  slippage_model: volume
  slippage_params:
    coefficient: 0.0005
