version: 1
matrices:
  default:
    description: "Standard nox session matrix for tests and linting"
    tool: nox
    sessions:
      - name: tests-3.11
        description: "Run pytest suite on Python 3.11"
      - name: tests-3.12
        description: "Run pytest suite on Python 3.12"
      - name: lint
        description: "Run lint checks"
  tox-release:
    description: "Release validation using tox environments"
    tool: tox
    environments:
      - name: lint
        description: "Static analysis lint env"
      - name: type
        description: "Type checking env"
      - name: package
        description: "Ensure package builds"
format:
  python:
    - scripts
  shell:
    - scripts
    - deploy
    - tools
units:
  conversions:
    - from: usd
      to: cents
      factor: 100
      description: "Dollar to cent conversion"
    - from: meter
      to: kilometer
      factor: 0.001
      description: "Distance conversion for analytics"
    - from: hour
      to: second
      factor: 3600
      description: "Time normalization for scheduling"
