name: CI Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  pytest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pytest with coverage
        run: pytest --cov=core/indicators --cov-report=term-missing --cov-report=xml
