name: Lint & Formatting

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  PIP_CACHE_DIR: ~/.cache/pip
  PYTHON_DEFAULT: '3.11'

jobs:
  lint:
    name: Run pre-commit suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_DEFAULT }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: >-
            ${{ runner.os }}-py${{ env.PYTHON_DEFAULT }}-lint-${{ hashFiles('requirements*.txt', 'pyproject.toml', '.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-py${{ env.PYTHON_DEFAULT }}-lint-
            ${{ runner.os }}-py${{ env.PYTHON_DEFAULT }}-

      - name: Install pre-commit tooling
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit (all files)
        run: |
          pre-commit run --all-files --show-diff-on-failure
