name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Update draft release notes
        uses: ./.github/actions/release-drafter-retry
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-name: release-drafter.yml
