name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run unit and integration tests with coverage
        run: |
          pytest tests/unit/ tests/integration/ tests/property/ tests/fuzz/ \
            --ignore=tests/unit/test_indicators_kuramoto.py \
            --ignore=tests/unit/test_kuramoto_ricci_composite.py \
            --ignore=tests/unit/test_indicators_ricci.py \
            --ignore=tests/unit/test_indicators_temporal_ricci.py \
            --cov=core --cov=backtest --cov=execution \
            --cov-report=xml --cov-report=term-missing \
            --cov-fail-under=56
      - name: Run property-based tests with statistics
        run: pytest tests/property/ --hypothesis-show-statistics
      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
