name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Cache pytest
        uses: actions/cache@v4
        with:
          path: .pytest_cache
          key: ${{ runner.os }}-pytest-${{ hashFiles('tests/**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-pytest-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip>=24.0
          pip install --prefer-binary -r requirements.txt
          pip install --prefer-binary -r requirements-dev.txt
      
      - name: Run unit and integration tests with coverage
        run: |
          pytest tests/unit/ tests/integration/ tests/property/ tests/fuzz/ \
            --ignore=tests/unit/test_indicators_kuramoto.py \
            --ignore=tests/unit/test_kuramoto_ricci_composite.py \
            --ignore=tests/unit/test_indicators_ricci.py \
            --ignore=tests/unit/test_indicators_temporal_ricci.py \
            --cov=core --cov=backtest --cov=execution \
            --cov-report=xml --cov-report=term-missing \
            --cov-fail-under=56
      
      - name: Cache coverage reports
        uses: actions/cache@v4
        with:
          path: coverage.xml
          key: ${{ runner.os }}-coverage-${{ github.sha }}
      
      - name: Run property-based tests with statistics
        run: pytest tests/property/ --hypothesis-show-statistics
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
