name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Prepare test report directories
        run: |
          mkdir -p reports
      - name: Run unit and integration tests with coverage
        run: |
          pytest tests/unit/ tests/integration/ tests/property/ tests/fuzz/ \
            --ignore=tests/unit/test_indicators_kuramoto.py \
            --ignore=tests/unit/test_kuramoto_ricci_composite.py \
            --ignore=tests/unit/test_indicators_ricci.py \
            --ignore=tests/unit/test_indicators_temporal_ricci.py \
            --cov=core --cov=backtest --cov=execution \
            --cov-report=xml --cov-report=term-missing --cov-report=html:coverage_html \
            --cov-fail-under=56 \
            --junitxml=reports/unit-integration-tests.xml \
            --html=reports/unit-integration-report.html --self-contained-html
      - name: Run property-based tests with statistics
        run: |
          pytest tests/property/ --hypothesis-show-statistics \
            --junitxml=reports/property-tests.xml \
            --html=reports/property-tests-report.html --self-contained-html
      - name: Upload JUnit test reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: |
            reports/unit-integration-tests.xml
            reports/property-tests.xml
          if-no-files-found: error
      - name: Upload HTML test reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-reports
          path: |
            reports/unit-integration-report.html
            reports/property-tests-report.html
          if-no-files-found: error
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            coverage_html
          if-no-files-found: error
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
